import os.path
import shutil

from skimage import io
from skimage.metrics import structural_similarity as ssim


def test_poly_new_minimal_ert_printscreen(
    opened_main_window_minimal_realizations, qtbot, source_root
):
    """This tests verifies that weights are stored in the metadata.json file
    when running esmda and that the content is read back and populated in the
    GUI when enabling restart functionality.
    """

    current_image_path = os.path.join(
        source_root,
        "docs",
        "ert",
        "getting_started",
        "configuration",
        "poly_new",
        "minimal",
        "ert.png",
    )

    gui = opened_main_window_minimal_realizations

    temp_image_path = qtbot.screenshot(gui)

    new_image = io.imread(temp_image_path, as_gray=True)
    current_image = io.imread(current_image_path, as_gray=True)

    significant_change = True

    if new_image.shape == current_image.shape:
        similarity_index = ssim(
            new_image, current_image, data_range=new_image.max() - new_image.min()
        )

        significant_change = (
            similarity_index <= 0.999999
        )  # This needs to be tuned. Minor changes like temp path is expected.

    if significant_change:
        shutil.move(temp_image_path, current_image_path)

    assert not significant_change, f"""
        The auto generated image differed from the current image used in the docs

        The image {current_image_path} has been overwritten with the new version.
        If the new version seems correct it should be kept.
        If the autogenerated image seems incorrect the underlying code generating the
        gui might need corrections or this test needs to be fixed.
        """
